title: TestBot Chronicles
description: A blog about QA, bugs, automation, and testing insights.
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
url: "https://anniejose212.github.io"
baseurl: "/testbotchronicles" 
author:
  name: Annie Jose
  bio: "QA Analyst | Testing | Blogging the journey"


