title: TestBot Chronicles
description: A blog about QA, bugs, automation insights
theme: jekyll-theme-slate
url: "https://anniejose212.github.io"
baseurl: "/testbotchronicles"
future: true
timezone: Australia/Melbourne



